# Generated by Django 5.0.7 on 2024-07-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
